apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
        - image: crudweasle/crud:html
          name: html
          ports:
            - containerPort: 80
